import { UnaryFunction } from './unary-function';

export interface Pipeline<Value = unknown> {
	pipe(): Value;
	pipe<A>(op1: UnaryFunction<Value, A>): A;
	pipe<A, B>(op1: UnaryFunction<Value, A>, op2: UnaryFunction<A, B>): B;
	pipe<A, B, C>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
	): C;
	pipe<A, B, C, D>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
	): D;
	pipe<A, B, C, D, E>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
	): E;
	pipe<A, B, C, D, E, F>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
	): F;
	pipe<A, B, C, D, E, F, G>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
	): G;
	pipe<A, B, C, D, E, F, G, H>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
	): H;
	pipe<A, B, C, D, E, F, G, H, I>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
	): I;
	pipe<A, B, C, D, E, F, G, H, I, J>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
	): J;
	pipe<A, B, C, D, E, F, G, H, I, J, K>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
	): K;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
	): L;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
	): M;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
	): N;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
	): O;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
	): P;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
	): Q;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
	): R;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
	): S;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
	): T;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
	): U;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
	): V;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
		op23: UnaryFunction<V, W>,
	): W;
	pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
		op23: UnaryFunction<V, W>,
		op24: UnaryFunction<W, X>,
	): X;
	pipe<
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
	>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
		op23: UnaryFunction<V, W>,
		op24: UnaryFunction<W, X>,
		op25: UnaryFunction<X, Y>,
	): Y;
	pipe<
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,
	>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
		op23: UnaryFunction<V, W>,
		op24: UnaryFunction<W, X>,
		op25: UnaryFunction<X, Y>,
		op26: UnaryFunction<Y, Z>,
	): Z;
	pipe<
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,
	>(
		op1: UnaryFunction<Value, A>,
		op2: UnaryFunction<A, B>,
		op3: UnaryFunction<B, C>,
		op4: UnaryFunction<C, D>,
		op5: UnaryFunction<D, E>,
		op6: UnaryFunction<E, F>,
		op7: UnaryFunction<F, G>,
		op8: UnaryFunction<G, H>,
		op9: UnaryFunction<H, I>,
		op10: UnaryFunction<I, J>,
		op11: UnaryFunction<J, K>,
		op12: UnaryFunction<K, L>,
		op13: UnaryFunction<L, M>,
		op14: UnaryFunction<M, N>,
		op15: UnaryFunction<N, O>,
		op16: UnaryFunction<O, P>,
		op17: UnaryFunction<P, Q>,
		op18: UnaryFunction<Q, R>,
		op19: UnaryFunction<R, S>,
		op20: UnaryFunction<S, T>,
		op21: UnaryFunction<T, U>,
		op22: UnaryFunction<U, V>,
		op23: UnaryFunction<V, W>,
		op24: UnaryFunction<W, X>,
		op25: UnaryFunction<X, Y>,
		op26: UnaryFunction<Y, Z>,
		...operations: ReadonlyArray<UnaryFunction>
	): unknown;
}

export interface PipelineConstructor {
	new <Value>(value: Value): Pipeline<Value>;
	readonly prototype: Pipeline;
}

export const Pipeline: PipelineConstructor = class<Value> {
	/** @internal */
	readonly #value: Value;

	/** @internal */
	constructor(value: Value) {
		this.#value = value;
	}

	/** @internal */
	pipe(...operations: []): Value;
	pipe(...operations: []): unknown {
		return operations.reduce(
			(acc, operation: UnaryFunction) => operation(acc),
			this.#value,
		);
	}
};
